### ISSUE TITLE
"includes" does not work with file patterns

### ISSUE THREAD

**Issue by jbarop** [heroku/heroku-maven-plugin#17]
According to the inline documentation `includes` is a `A set of file patterns to include in the zip.` But I think it's used as a list of file paths.

````
Caused by: java.io.IOException: There was an error packaging the application for deployment.
	at com.heroku.sdk.deploy.App.prepare(App.java:138)
	at com.heroku.sdk.maven.MavenApp.prepare(MavenApp.java:22)
	at com.heroku.sdk.deploy.App.deploy(App.java:80)
	at com.heroku.sdk.deploy.App.deploy(App.java:87)
	at com.heroku.sdk.maven.DeployMojo.execute(DeployMojo.java:38)
	... 21 more
Caused by: java.nio.file.NoSuchFileException: ../service/target/*.shaded.jar
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at com.heroku.sdk.deploy.App.copy(App.java:147)
	at com.heroku.sdk.deploy.App.prepare(App.java:129)
```

It would be indeed cool to have `includes` work with file patters.

**Comment by jkutner** [comment]
Thanks for reporting this!
