### ISSUE TITLE
"no !/ in spec" error

### ISSUE THREAD

**Issue by mmoayyed** [heroku/heroku-maven-plugin#21]
I have the following configuration in my pom:

```xml
<plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.10</version>
        <executions>
          <execution>
            <id>copy-dependencies</id>
            <phase>package</phase>
            <goals>
              <goal>copy</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>com.github.jsimone</groupId>
                  <artifactId>webapp-runner</artifactId>
                  <version>8.0.23.0</version>
                  <destFileName>webapp-runner.jar</destFileName>
                </artifactItem>
              </artifactItems>
              <includeScope>compile</includeScope>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

When I run the following command in terminal:

```
java -jar target\dependency\webapp-runner.jar --port 8080 target\cas.war

```

I get

```
Adding Context  for c:\Misagh\GitWorkspace\cas-server\cas-server-webapp\target\heroku\app\target\cas.war
Aug 12, 2015 8:16:25 AM org.apache.coyote.AbstractProtocol init
INFO: Initializing ProtocolHandler ["http-nio-8080"]
Aug 12, 2015 8:16:25 AM org.apache.tomcat.util.net.NioSelectorPool getSharedSelector
INFO: Using a shared selector for servlet write/read
Aug 12, 2015 8:16:25 AM org.apache.catalina.core.StandardService startInternal
INFO: Starting service Tomcat
Aug 12, 2015 8:16:25 AM org.apache.catalina.core.StandardEngine startInternal
INFO: Starting Servlet Engine: Apache Tomcat/8.0.23
Aug 12, 2015 8:16:28 AM org.apache.catalina.startup.ContextConfig getDefaultWebXmlFragment
INFO: No global web.xml found
Aug 12, 2015 8:16:31 AM org.apache.catalina.startup.ContextConfig processServletContainerInitializers
SEVERE: Failed to process JAR found at URL [] for ServletContainerInitializers for context with name [{1}]
java.net.MalformedURLException: no !/ in spec
        at java.net.URL.<init>(URL.java:620)
        at java.net.URL.<init>(URL.java:483)
        at java.net.URL.<init>(URL.java:432)
        at java.net.JarURLConnection.parseSpecs(JarURLConnection.java:175)
        at java.net.JarURLConnection.<init>(JarURLConnection.java:158)
        at sun.net.www.protocol.jar.JarURLConnection.<init>(JarURLConnection.java:81)
        at sun.net.www.protocol.jar.Handler.openConnection(Handler.java:41)
        at java.net.URL.openConnection(URL.java:972)
        at java.net.URL.openStream(URL.java:1038)
        at org.apache.catalina.startup.WebappServiceLoader.parseConfigFile(WebappServiceLoader.java:161)
        at org.apache.catalina.startup.WebappServiceLoader.load(WebappServiceLoader.java:118)
        at org.apache.catalina.startup.ContextConfig.processServletContainerInitializers(ContextConfig.java:1616)
        at org.apache.catalina.startup.ContextConfig.webConfig(ContextConfig.java:1128)
        at org.apache.catalina.startup.ContextConfig.configureStart(ContextConfig.java:771)
        at org.apache.catalina.startup.ContextConfig.lifecycleEvent(ContextConfig.java:305)
        at org.apache.catalina.util.LifecycleSupport.fireLifecycleEvent(LifecycleSupport.java:117)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:90)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5066)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1399)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException: no !/ in spec
        at sun.net.www.protocol.jar.Handler.parseAbsoluteSpec(Handler.java:171)
        at sun.net.www.protocol.jar.Handler.parseURL(Handler.java:151)
        at java.net.URL.<init>(URL.java:615)
        ... 24 more
```

What seems to be the problem?

**Comment by mmoayyed** [comment]
This is with Java 1.8 and Maven 3.3.3

**Comment by jkutner** [comment]
@mmoayyed are you using the heroku-maven-plugin too? You shouldn't need this configuration as the plugin copies webapp-runner for you.

Regardless, try adding `--expand-war` to your webapp-runner options.

**Comment by mmoayyed** [comment]
Yes, I had this right above it:

```
<plugin>
        <groupId>com.heroku.sdk</groupId>
        <artifactId>heroku-maven-plugin</artifactId>
        <configuration>
          <appName>jasigcas</appName>
        </configuration>
      </plugin>
```

What I did was I ran `mvn heroku:deploy-war`, stopped the upload the tried to run the commands above. I was doing this because `mvn heroku:run-war` was exhibiting the same error stack. 

Adding that option to the command prompt did the trick. Thank you. I am assuming the same option should be added to my Procfile, right? 

Also, how can I then make  `mvn heroku:run-war`  work with the same option?

**Comment by mmoayyed** [comment]
This did the trick. Would be great to document it:

```
      <plugin>
        <groupId>com.heroku.sdk</groupId>
        <artifactId>heroku-maven-plugin</artifactId>
        <configuration>
          <appName>jasigcas</appName>
          <configVars>
            <WEBAPP_RUNNER_OPTS>--expand-war</WEBAPP_RUNNER_OPTS>
          </configVars>
        </configuration>
      </plugin>
```

This is with the latest version of the plugin, 0.4.4. 

Thank you.

**Comment by jkutner** [comment]
Yes, that looks correct. Sorry for the trouble -- i'll find a place to document this. 

Also, the latest version of the plugin is `0.5.1`, which uses Tomcat 8 by default.

**Comment by mmoayyed** [comment]
Sweet. I'll be upgrading to that shortly.

**Comment by mmoayyed** [comment]
Also, let me document that for a successful heroku deployment, the dependency module is required to copy the runner. Otherwise the heroku will crash. 

Closing this.
