### ISSUE TITLE
Connection timed out error when behind a proxy

### ISSUE THREAD

**Issue by pmorddny** [heroku/heroku-maven-plugin#26]
Hi, I'm behind a corporate proxy and I get the following error when I run a mvn heroku:deploy from the command line or from within Eclipse:

`Caused by: org.apache.http.conn.HttpHostConnectException: Connect to api.heroku.com:443 [api.heroku.com/75.101.133.143, api.heroku.com/107.20.244.238, api.heroku.com/54.243.76.42] failed: Connection timed out: connect
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.heroku.sdk.deploy.utils.RestClient.get(RestClient.java:29)
	at com.heroku.sdk.deploy.ConfigVars.getConfigVars(ConfigVars.java:41)
	at com.heroku.sdk.deploy.ConfigVars.merge(ConfigVars.java:24)
	at com.heroku.sdk.deploy.Deployer.mergeConfigVars(Deployer.java:103)
	at com.heroku.sdk.deploy.Deployer.deploy(Deployer.java:67)
	at com.heroku.sdk.deploy.App.deploy(App.java:57)
	at com.heroku.sdk.deploy.App.deploy(App.java:61)
	at com.heroku.sdk.maven.DeployMojo.execute(DeployMojo.java:49)`

**Comment by jkutner** [comment]
Working on this in c3638bb4b91092988697a8c223f5bc6696a80e1c

**Comment by jkutner** [comment]
I've put a fix in version 1.0.2 that uses `HTTP_PROXY` and `HTTPS_PROXY` as described in [CLI Usage](https://devcenter.heroku.com/articles/using-the-cli#using-an-http-proxy). Please give this a try and let me know if it works or not.

**Comment by jkutner** [comment]
@pmorddny ^^

**Comment by kenya44** [comment]
I'm encountering a similar connection timeout issue when issuing:

$ heroku deploy:war --war <war_file_location> --app  <app_name>

Exception in thread "main" java.net.ConnectException: Connection timed out: connect
        at java.net.DualStackPlainSocketImpl.connect0(Native Method)
        at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
        at sun.net.www.http.HttpClient.New(HttpClient.java:308)
        at sun.net.www.http.HttpClient.New(HttpClient.java:326)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1513)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.URL.openStream(URL.java:1045)
        at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1460)
        at com.heroku.sdk.deploy.DeployWar.<init>(DeployWar.java:21)
        at com.heroku.sdk.deploy.DeployWar.main(DeployWar.java:74)

   ***
From the stack trace, it appears that proxy handling needs to be added to 
DeployWar.java =>  FileUtils.copyURLToFile(webappRunnerUrl, webappRunnerJar);

**Comment by jkutner** [comment]
@kenya44 I see what's going on now. Thanks for narrowing this down. I'll try to get a fix out soon.

**Comment by jkutner** [comment]
@kenya44 if you set the environment variable `JAVA_TOOL_OPTIONS="-Dhttp.proxyHost=proxyserver.com  -Dhttp.proxyPort=8080"` does the `heroku deploy:war` command work? (if so I can build that into the code).

**Comment by kenya44** [comment]
This solution works on RHEL (OpenJDK Runtime Environment (build 1.8.0_91-b14)), but not on Windows 7 64-bit (Java(TM) SE Runtime Environment (build 1.8.0_72-b15)).   On Windows, the JVM fails to parse the -Dhttp.proxyPort=8080 as a second system property, but instead it shows up as a single system property:
    http.proxyHost=proxyserver.com -Dhttp.proxyPort=8080
The workaround was to just specify only the proxyHost parameter since our proxy server uses the default proxy port=80.  At this point, I'm fine with manually setting the JAVA_TOOL_OPTIONS environment variable until Oracle fixes their Windows JVM bug.

**Comment by jkutner** [comment]
@kenya44 ah, that's great to know because I can fix it now. I can set `http.proxyPort` `and http.proxyHost` dynamically in `DeployJar` from the environment variables. Thank you for this excellent report. I will have a fix out soon.

**Comment by jkutner** [comment]
This fix has been updated and released in the heroku-deploy library, the Heroku Maven plugin, and the heroku-deploy CLI plugin. I'm going to close the ticket, but please let me know if you have any more problems and we'll reopen it.

**Comment by mushroomlb** [comment]
删除项目目录下的.mvn和maven.exe，这样使用系统的mvn命令就没有问题了
