### ISSUE TITLE
Support git ssh url

### ISSUE THREAD

**Issue by yorlov** [heroku/heroku-maven-plugin#35]
heroku app url is **ssh://git@heroku.com/app.git**
run `sbt stage deployHeroku`
result
> [info] -----> Packaging application...
> [info]        - app: null
> [info]        - including: target/universal/stage/
> java.lang.NullPointerException
>     at java.net.URLEncoder.encode(URLEncoder.java:204)
>     at com.heroku.sdk.deploy.ConfigVars.getConfigVars(ConfigVars.java:35)
>     at com.heroku.sdk.deploy.ConfigVars.merge(ConfigVars.java:24)
>     at com.heroku.sdk.deploy.Deployer.mergeConfigVars(Deployer.java:103)
>     at com.heroku.sdk.deploy.Deployer.deploy(Deployer.java:67)
>     at com.heroku.sdk.deploy.App.deploy(App.java:57)
>     at com.heroku.sbt.SbtApp.deploy(SbtApp.scala:101)
>     at com.heroku.sdk.deploy.App.deploy(App.java:61)
>     at com.heroku.sbt.HerokuPlugin$autoImport$$anonfun$baseHerokuSettings$2.apply(HerokuPlugin.scala:40)
>     at com.heroku.sbt.HerokuPlugin$autoImport$$anonfun$baseHerokuSettings$2.apply(HerokuPlugin.scala:26)
>     at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
>     at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
>     at sbt.std.Transform$$anon$4.work(System.scala:63)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
>     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:228)
>     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
>     at sbt.Execute.work(Execute.scala:237)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
>     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:228)
>     at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
>     at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>     at java.lang.Thread.run(Thread.java:745)
> java.lang.NullPointerException
>     at java.nio.charset.CharsetEncoder.canEncode(CharsetEncoder.java:984)
>     at sbt.IO$.writer(IO.scala:690)
>     at sbt.IO$.write(IO.scala:687)
>     at com.heroku.sbt.HerokuLogger.trace(HerokuPlugin.scala:118)
>     at sbt.AbstractLogger.log(Logger.scala:29)
>     at sbt.MultiLogger$$anonfun$dispatch$1.apply(MultiLogger.scala:37)
>     at sbt.MultiLogger$$anonfun$dispatch$1.apply(MultiLogger.scala:33)
>     at scala.collection.immutable.List.foreach(List.scala:318)
>     at sbt.MultiLogger.dispatch(MultiLogger.scala:33)
>     at sbt.MultiLogger.trace(MultiLogger.scala:26)
>     at sbt.EvaluateTask$$anonfun$logIncomplete$2.apply(EvaluateTask.scala:294)
>     at sbt.EvaluateTask$$anonfun$logIncomplete$2.apply(EvaluateTask.scala:289)
>     at scala.collection.TraversableLike$WithFilter$$anonfun$foreach$1.apply(TraversableLike.scala:772)
>     at scala.collection.immutable.List.foreach(List.scala:318)
>     at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:771)
>     at sbt.EvaluateTask$.logIncomplete(EvaluateTask.scala:289)
>     at sbt.EvaluateTask$.logIncResult(EvaluateTask.scala:282)
>     at sbt.EvaluateTask$.run$1(EvaluateTask.scala:365)
>     at sbt.EvaluateTask$.runTask(EvaluateTask.scala:378)
>     at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:69)
>     at sbt.Aggregation$$anonfun$3.apply(Aggregation.scala:67)
>     at sbt.EvaluateTask$.withStreams(EvaluateTask.scala:314)
>     at sbt.Aggregation$.timedRun(Aggregation.scala:67)
>     at sbt.Aggregation$.runTasks(Aggregation.scala:76)
>     at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:37)
>     at sbt.Aggregation$$anonfun$applyTasks$1.apply(Aggregation.scala:36)
>     at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
>     at sbt.Command$$anonfun$applyEffect$2$$anonfun$apply$3.apply(Command.scala:61)
>     at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:158)
>     at sbt.Aggregation$$anonfun$evaluatingParser$4$$anonfun$apply$5.apply(Aggregation.scala:157)
>     at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:253)
>     at sbt.Act$$anonfun$sbt$Act$$actParser0$1$$anonfun$sbt$Act$$anonfun$$evaluate$1$1$$anonfun$apply$10.apply(Act.scala:250)
>     at sbt.Command$.process(Command.scala:93)
>     at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
>     at sbt.MainLoop$$anonfun$1$$anonfun$apply$1.apply(MainLoop.scala:96)
>     at sbt.State$$anon$1.doX$1(State.scala:183)
>     at sbt.State$$anon$1.process(State.scala:190)
>     at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
>     at sbt.MainLoop$$anonfun$1.apply(MainLoop.scala:96)
>     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
>     at sbt.MainLoop$.next(MainLoop.scala:96)
>     at sbt.MainLoop$.run(MainLoop.scala:89)
>     at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:68)
>     at sbt.MainLoop$$anonfun$runWithNewLog$1.apply(MainLoop.scala:63)
>     at sbt.Using.apply(Using.scala:24)
>     at sbt.MainLoop$.runWithNewLog(MainLoop.scala:63)
>     at sbt.MainLoop$.runAndClearLast(MainLoop.scala:46)
>     at sbt.MainLoop$.runLoggedLoop(MainLoop.scala:30)
>     at sbt.MainLoop$.runLogged(MainLoop.scala:22)
>     at sbt.StandardMain$.runManaged(Main.scala:109)
>     at sbt.xMain.run(Main.scala:38)
>     at xsbt.boot.Launch$$anonfun$run$1.apply(Launch.scala:109)
>     at xsbt.boot.Launch$.withContextLoader(Launch.scala:128)
>     at xsbt.boot.Launch$.run(Launch.scala:109)
>     at xsbt.boot.Launch$$anonfun$apply$1.apply(Launch.scala:35)
>     at xsbt.boot.Launch$.launch(Launch.scala:117)
>     at xsbt.boot.Launch$.apply(Launch.scala:18)
>     at xsbt.boot.Boot$.runImpl(Boot.scala:41)
>     at xsbt.boot.Boot$.main(Boot.scala:17)
>     at xsbt.boot.Boot.main(Boot.scala)
> [error] java.lang.NullPointerException
> [error] Use 'last' for the full log.

**Comment by Malax** [comment]
Since this issue had no activity in years, I'll close it. The reported problem should be fixed in `2.x`, feel free to reopen if not. :)
